leasing_payment:
    resource: "@LeasingPaymentBundle/Resources/config/routing.yml"
    prefix:   /payment

leasing_sms:
    resource: "@LeasingSmsBundle/Resources/config/routing.yml"
    prefix:   /sms

leasing_property:
    resource: "@LeasingPropertyBundle/Resources/config/routing.yml"
    prefix:   /property

