leasing_property_homepage:
    path:     /
    defaults: { _controller: LeasingPropertyBundle:Main:index }

leasing_property_update_unit:
    path:     /search
    defaults: { _controller: LeasingPropertyBundle:Main:searchProperty }

leasing_property_update_unit:
    path:     /save-unit
    defaults: { _controller: LeasingPropertyBundle:Main:saveProperty }

leasing_property_update_calendar:
    path:     /save-calendar
    defaults: { _controller: LeasingPropertyBundle:Main:saveCalendar }

leasing_property_update_event:
    path:     /save-event
    defaults: { _controller: LeasingPropertyBundle:Main:saveEvent }

leasing_property_save_parking_lead:
    path:     /parking-application
    defaults: { _controller: LeasingPropertyBundle:Parking:saveParkingLead }

leasing_property_save_appointment_request:
    path:     /appointment-request
    defaults: { _controller: LeasingPropertyBundle:Residential:saveAppointmentRequest }

leasing_property_save_event_lead:
    path:     /reserve-event
    defaults: { _controller: LeasingPropertyBundle:Event:saveEventBooking }