leasing_payment_retrieve_application:
    path:     /retrieve-application
    defaults: { _controller: LeasingPaymentBundle:Payment:retrieveApplication }

leasing_payment_checkout:
    path:     /checkout
    defaults: { _controller: LeasingPaymentBundle:Payment:paymaya }

leasing_payment_success:
    path:     /success
    defaults: { _controller: LeasingPaymentBundle:Payment:paymayaSuccess }

leasing_payment_failure:
    path:     /failure
    defaults: { _controller: LeasingPaymentBundle:Payment:paymayaFailure }

leasing_payment_cancel:
    path:     /failure
    defaults: { _controller: LeasingPaymentBundle:Payment:paymayaCancel }